export const titles = [
    'browsers', 'operating system', 'software development','terminal', 'programing languages'
]

export const links = [
    {
        id: 'browsers',
        articles: "Articles",
        videos:"Videos",
        link1:'https://www.lifewire.com/what-is-a-browser-446234',
        link2:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        link3:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        link4:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        video1:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        video2:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        video3:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        video4:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
    },
    {
        id: 'operating system',
        articles: "Articles",
        videos:"Videos",
        link1:'https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'software development',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'terminal',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'software development',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'programing languages',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'python',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'java-script',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'java',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'angular',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'vue',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'react',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },



]
