export const links = [
    {
        id: 'why learn web basics?',
    },
    {
        id: 'web server / web host / server',
        articles: "Articles",
        videos:"Videos",
        link1:'https://whatis.techtarget.com/definition/Web-server',
        link2:"https://economictimes.indiatimes.com/definition/web-server",
        link3:"https://www.webopedia.com/TERM/W/Web_server.html",
        video1:"https://www.khanacademy.org/computing/computer-science/internet-intro/internet-works-intro/v/the-internet-http-and-html",
    },
    {
        id: 'browsers',
        articles: "Articles",
        videos:"Videos",
        link1:'https://www.lifewire.com/what-is-a-browser-446234',
        link2:"https://www.computerhope.com/jargon/b/browser.htm",
        link3:"https://techterms.com/definition/web_browser",
        video1:"https://www.youtube.com/watch?v=BrXPcaRlBqo",
        video2:"https://www.youtube.com/watch?v=z0HN-fG6oT4",
        video3:"https://www.youtube.com/watch?v=AGGWCbMvOxA",
    },
    {
        id: 'operating system',
        articles: "Articles",
        videos:"Videos",
        link1:'https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/',
        link2:"https://www.lifewire.com/operating-systems-2625912",
        link3:"https://www.geeksforgeeks.org/introduction-of-operating-system-set-1/",
        link4:"https://www.computerhope.com/jargon/o/os.htm",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=GjNp0bBrjmU",
    },
    {
        id: 'software development',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://www.ibm.com/topics/software-development",
        video1:"https://www.youtube.com/watch?v=ilgO5TdRf_M",
        video3:"https://www.youtube.com/watch?v=FCMxA3m_Imc",
        video4:"https://www.youtube.com/watch?v=6tZz6gr1h9E",
    },
    {
        id: 'terminal',
        articles: "Articles",
        videos:"Videos",
        link1:'https://code.tutsplus.com/tutorials/command-line-basics-and-useful-tricks-with-the-terminal--cms-29356',
        link2:"https://www.hongkiat.com/blog/developers-command-line/",
        link3:"https://itconnect.uw.edu/learn/workshops/online-tutorials/web-publishing/what-is-a-terminal/",
        link4:"https://techterms.com/definition/terminal",
        video1:"https://www.youtube.com/watch?v=5XgBd6rjuDQ&t=2s",

    },
    {
        id: 'programing languages',
        articles: "Articles",
        videos:"Videos",
        link1:"https://www.programmingforbeginnersbook.com/blog/what_is_programming_coding/",
        link2:"https://searchsoftwarequality.techtarget.com/definition/program",
        link3:"https://www.webopedia.com/TERM/P/programming_language.html",
        link4:"https://techterms.com/definition/programming_language",
        video1:"https://www.youtube.com/watch?v=fbZ4ZhzCeR4",
        video2:"https://www.youtube.com/watch?v=_zusEe3GOe8",
    },
    {
        id: 'what-language-should-i-learn',
        articles: "Articles",
        videos:"Videos",
        link1:"https://blog.teamtreehouse.com/choose-programming-language",
        link2:"https://www.freecodecamp.org/news/how-to-choose-which-programming-language-you-should-learn-in-2019-60abef241012/",
        link3:"https://medium.com/the-mission/how-to-choose-which-programming-language-to-learn-infographic-46f7874bd02",
        link4:"https://opensource.com/article/17/1/choosing-your-first-programming-language",
        video1:"https://www.youtube.com/watch?v=2EaopRDxNrw",
        video2:"https://www.youtube.com/watch?v=poJfwre2PIs",
        video3:"https://www.youtube.com/watch?v=iH4JJuoHQHc",
        video4:"https://www.youtube.com/watch?v=d7nxcC9i6t8",
        video5:"https://www.youtube.com/watch?v=QUPZvJPKd8A"
    },
    {
        id: 'python',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'java-script',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'java',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'angular',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'vue',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },
    {
        id: 'react',
        articles: "Articles",
        videos:"Videos",
        link1:'https://searchapparchitecture.techtarget.com/definition/software',
        link2:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link3:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        link4:"https://edu.gcfglobal.org/en/computerbasics/understanding-operating-systems/1/",
        video1:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video2:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video3:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
        video4:"https://www.youtube.com/watch?v=pTdSs8kQqSA",
    },



]
